# Simple experiments & profiling (no checkpointing anywhere)

experiments:
  - name: "amp_on"
    overrides:
      hardware.amp: true

profile:
  # AMP profiling
  amp:
    values: [true, false]
    param: "train.amp_profile"

  # Sequence length profiling
  seq_len:
    values: [256, 512, 1024, 2048]
    param: "data.seq_len"

  # Batch size profiling
  batch_size:
    values: [4, 8, 16, 32]
    param: "train.batch_size"

run:
  steps: 500
  log_every: 100
